Neos:
  Flow:
    error:
      exceptionHandler:

        # Defines the global, last-resort exception handler.
        # The specified class must implement \Neos\Flow\Error\ExceptionHandlerInterface
        className: Langeland\Liquid\Error\ProductionExceptionHandler

        # default options for all rendering groups (see below). Options can be overridden in the respective rendering group

        # Rendering groups can define special renderings depending on status code or class of the
        # thrown exception.
        renderingGroups:
          notFoundExceptions:
            options:
              templatePathAndFilename: 'resource://Langeland.Liquid/Private/Templates/Error/Default.html'

          databaseConnectionExceptions:
            options:
              templatePathAndFilename: 'resource://Langeland.Liquid/Private/Templates/Error/Default.html'
